name = "quida-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"

[vars]
ALTIFIED_BACKEND = "https://api.altified.com"
ALTIFIED_API_KEY = "93b5e304a9494a8aa87ea2e71bf8bebe"
DOMAIN = "quida.app"